### ISSUE TITLE
installExtensionByName doesn't work in vso-node-api@6.2.5-preview

### ISSUE THREAD

**Issue by youngbupark** [Microsoft/vsts-node-api#106]
```
Error: No api-version was supplied for the "POST" request. The version must be supplied either as part of the Accept header (e.g. "application/json; api-version=1.0") or as a query parameter (e.g. "?api-version=1.0").
    at RestClient.<anonymous> (/Users/youngp/ci/vsts-test/node_modules/typed-rest-client/RestClient.js:173:28)
    at next (native)
    at fulfilled (/Users/youngp/ci/vsts-test/node_modules/typed-rest-client/RestClient.js:6:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

looks like extension install Rest API doesn't have `3.2-preview.1` version which vso-node-api@6.2.5 uses.
it is working with 3.0-preview.1 api-version in vso-node-api@5.1.2

**Comment by stephenmichaelf** [comment]
@youngbupark Could you get the latest 6.3.0-preview version and see if this works now?

**Comment by stephenmichaelf** [comment]
Going to close for now, please reopen with additional details if you are still having issues.
