### ISSUE TITLE
installExtensionByName returns error "invalid resource"

### ISSUE THREAD

**Issue by myunggeun-song** [Microsoft/vsts-node-api#110]
The same code that works correctly in vso-node-api v5.1.2 doesn't work in v6.0.0. 

The API is `IExtensionManagementApi.installExtensionByName` and the extension is `publisherName: ms-devlabs`, `extensionName: FolderManagement`. I tested the other extension but it also received the same "invalid resource" error.

```
error: Failed to install extention error : { Error: invalid resource
    at RestCallbackClient._sendJson (/Users/morgan/work/pirate_spaceship/work/tmp/ci-accounts-service/node_modules/vso-node-api/RestClient.js:120:19)
    at RestCallbackClient.create (/Users/morgan/work/pirate_spaceship/work/tmp/ci-accounts-service/node_modules/vso-node-api/RestClient.js:72:14)
    at /Users/morgan/work/pirate_spaceship/work/tmp/ci-accounts-service/node_modules/vso-node-api/ExtensionManagementApi.js:582:30
    at _fulfilled (/Users/morgan/work/pirate_spaceship/work/tmp/ci-accounts-service/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/morgan/work/pirate_spaceship/work/tmp/ci-accounts-service/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/morgan/work/pirate_spaceship/work/tmp/ci-accounts-service/node_modules/q/q.js:816:13)
    at /Users/morgan/work/pirate_spaceship/work/tmp/ci-accounts-service/node_modules/q/q.js:624:44
    at runSingle (/Users/morgan/work/pirate_spaceship/work/tmp/ci-accounts-service/node_modules/q/q.js:137:13)
    at flush (/Users/morgan/work/pirate_spaceship/work/tmp/ci-accounts-service/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9) statusCode: undefined }
```

**Comment by stephenmichaelf** [comment]
Thanks for letting us know @myunggeun-song. I will try to recreate and see what's going on. Note that this library has been in preview for a while and it's possible that functionality changes over time.

**Comment by stephenmichaelf** [comment]
@damccorm Can you take a look?
