### ISSUE TITLE
ServiceHooks - api location error

### ISSUE THREAD

**Issue by helaili** [Microsoft/vsts-node-api#123]
I'm successfully accessing the Build API on VSTS. Now trying to use the ServiceHooks one I'm getting the following error: 

``` 
 Promise {
    <rejected> Error: Failed to find api location for area: hookssvc id: 4431ee3f-13e3-4b41-b62e-47289e90d3dc
      at beginGetLocation.then (/Users/alain/Documents/workspace/vsts-octobot/node_modules/vso-node-api/VsoClient.js:84:27)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7) }
  --
  Error: Failed to find api location for area: hookssvc id: 4431ee3f-13e3-4b41-b62e-47289e90d3dc
      at beginGetLocation.then (/Users/alain/Documents/workspace/vsts-octobot/node_modules/vso-node-api/VsoClient.js:84:27)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
``` 

Here is the code I'm using: 

```
let authHandler = vsts.getPersonalAccessTokenHandler(vstsToken)
let webApi = new vsts.WebApi(collectionUrl, authHandler)

let vstsBuildApi = webApi.getBuildApi()
vstsBuildApi.getDefinition(buildDefinitionId, project).then((def) => {
    // That works
    console.log(def)
})

let vstsServiceHookApi = webApi.getServiceHooksApi()
vstsServiceHookApi.listSubscriptions()
```

I did successfully used the REST API directly though (using Postman), so I'm sure my token is valid. Any idea anyone?

**Comment by stephenmichaelf** [comment]
@helaili  Could you get the latest 6.3.0-preview version and see if this works now?

npm install vso-node-api@preview

**Comment by stephenmichaelf** [comment]
This should be resolved in the latest version of the library. Please give that a try. If you are still having issues reopen this and I can take a look.
