### ISSUE TITLE
coreApi.getProjectCollections always returns an error 

### ISSUE THREAD

**Issue by Zenasoft** [Microsoft/vsts-node-api#40]
Failed to find api location for area: core id: 8031090f-ef1d-4af6-85fc-698cd75d42bf

**Comment by chrismbarr** [comment]
yes, same for me.  Is there a workaround for this?

Here's the error details I get
```
{ Error: Failed to find api location for area: core id: 8031090f-ef1d-4af6-85fc-698cd75d42bf
    at C:\<my-project>\node_modules\vso-node-api\VsoClient.js:65:23
    at _fulfilled (C:\<my-project>\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\<my-project>\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\<my-project>\node_modules\q\q.js:796:13)
    at C:\<my-project>\node_modules\q\q.js:604:44
    at runSingle (C:\<my-project>\node_modules\q\q.js:137:13)
    at flush (C:\<my-project>\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) statusCode: undefined }
```

**Comment by bryanmacfarlane** [comment]
That means the server doesn't have those REST APIs.  What server version are you targeting?

**Comment by chrismbarr** [comment]
An error message with details like what you just said would be much more helpful!  

We are using TFS 2017 that we host ourselves.
```
Microsoft Visual Studio Team Foundation Server
Version 15.105.25910.0 (Version 15.105.25910.0)
```

**Comment by stephenmichaelf** [comment]
Looks like we know the root cause, please let me know if you have other questions.
